### ISSUE TITLE
Settings Button

### ISSUE THREAD

**Issue by almorsey** [almorsey/TeaseMe#1]
Make the settings activity

**Comment by xtciaan** [comment]
The settings button still do not work? App crashes when pressed?

**Comment by almorsey** [comment]
https://drive.google.com/file/d/1n6Pno2uPBBXau3TX9voRlp57Vf9zVz4H/view?usp=drivesdk

Can you try this? I haven't looked at this code in about 2 years but I keep the APK. You have to manually open Android settings for this app after installing and allow storage but everything else works fine. Some flash teases don't get parsed and they introduced new EOS teases which are also not supported

**Comment by xtciaan** [comment]
Cool!!! Settings works.. on that apk.. what code has changed? Also downloading teases crashed before .. if you can have a look?
